replicaCount: 1

image:
  repository: cs3org/revad
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  grpc:
    port: 19000
  http:
    port: 19001

# https://reva.link/docs/config/
configFiles:
  revad.toml: |
    [grpc.services.gateway]
    [grpc.services.storageregistry]
    [grpc.services.storageprovider]
    [grpc.services.authprovider]
    [grpc.services.authregistry]
    [grpc.services.userprovider]
    [grpc.services.usershareprovider]
    [grpc.services.publicshareprovider]

    [http.services.dataprovider]
    [http.services.prometheus]


