{{- with .Values.wopibridge }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wopiserver.fullname" $ }}-{{ .name }}-secret
  labels:
    {{- include "wopibridge.labels" $ | nindent 4 }}
type: Opaque
data:
  {{ if .wbsecret }}
  wbsecret: "{{ .wbsecret | b64enc }}"
  {{ else }}
  wbsecret: "{{ randAlphaNum 24 | b64enc }}"
  {{ end }}
{{- end }}
{{- end }}
