apiVersion: v2
name: wopiserver
description: A Vendor-neutral Web-application Open Platform Interface (WOPI) gateway for EFSS systems
type: application
version: 0.5.0
appVersion: v8.3.2
kubeVersion: ">= 1.19.0"
home: https://github.com/cs3org/wopiserver
sources:
  - https://github.com/cs3org/wopiserver
maintainers:
  - name: SamuAlfageme
    email: samuel.alfageme.sainz@cern.ch
  - name: glpatcern
    email: giuseppe.lopresti@cern.ch
keywords:
  - wopi
  - efss
annotations:
  artifacthub.io/changes: |
    - "Switch to newer CS3org WOPI server version."
  artifacthub.io/images: |
    - name: wopiserver
      image: cs3org/wopiserver:v8.3.2
  artifacthub.io/containsSecurityUpdates: "false"
