replicaCount: 1

image:
  repository: cs3org/wopiserver
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8880

extraVolumeMounts: []
extraVolumes: []

env: []

# WOPISERVER's primary configuration
# - ref: https://github.com/cs3org/wopiserver/blob/master/wopiserver.conf
config:
  appProviders:
    codimdurl: http://codimd.local
  cs3:
    revahost: revad:19000
  loglevel: Debug

ingress:
  enabled: false
  hostname: wopi.local
  path: /wopi
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls: []
    # Secrets must be present in the namespace beforehand.
    # - secretName: wopi-tls
    #   hosts:
    #     - wopi.local

wopibridge:
  enabled: false
  name: wopibridge
  replicaCount: 1
  image:
    repository: cs3org/wopibridge
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8000

  extraVolumes: []
    # - name: image-store
    #   persistentVolumeClaim:
    #     claimName: image-store

  extraVolumeMounts: []
    # - name: image-store
    #   mountPath: /mnt/codimd_storage

  env: []
    # CODIMD_INT_URL: http://codimd
    # CODIMD_EXT_URL: https://codimd.local/path
    # CODIMD_STORAGE_PATH: /mnt/codimd_storage

  ingress:
    enabled: false
    hostname: bridge.local
    path: /wopibridge
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls: []
      # Secrets must be present in the namespace beforehand.
      # - secretName: bridge-tls
      #   hosts:
      #     - wopi.local
