replicaCount: 1

image:
  repository: cs3org/wopiserver
  tag: v8.3.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8880

## Overrides the default URL generation based on the ingress/service values
# wopiserverUrl: https://wopi.local/

extraVolumeMounts: []
extraVolumes: []

env: []

# WOPI server configuration
# - ref: https://github.com/cs3org/wopiserver/blob/master/wopiserver.conf
config:
  wopiSecret:
  logLevel: Error
  token:
    validity: 86400
  wopi:
    lock:
      expiration: 3600
  enableRename: False
  detectExternalLocks: False
  cs3:
    authTokenValidity: 3600
    gateway: revad:19000
    sslVerify: True

ingress:
  enabled: false
  hostname: wopi.local
  path: /wopi
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls: []
    # Secrets must be present in the namespace beforehand.
    # - secretName: wopi-tls
    #   hosts:
    #     - wopi.local
