apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wopiserver.fullname" . }}
  labels:
    {{- include "wopiserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wopiserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wopiserver.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
          fsGroup: {{ $.Values.securityContext.fsGroup }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ $.Values.securityContext.runAsUser }}
            runAsGroup: {{ $.Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          resources: {{ toYaml $.Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 8880
              protocol: TCP
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: log-volume
              mountPath: /var/log/wopi/
            - name: recovery-volume
              mountPath: /var/spool/wopirecovery/
            - name: {{ include "wopiserver.fullname" . }}-confdir
              mountPath: /etc/wopi/wopiserver.conf
              subPath: wopiserver.conf
            - name: {{ include "wopiserver.fullname" . }}-confdir
              mountPath: /etc/wopi/wopisecret
              subPath: wopisecret
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: log-volume
          emptyDir: {}
        - name: recovery-volume
          emptyDir: {}
        - name: {{ include "wopiserver.fullname" . }}-confdir
          projected:
            sources:
              - configMap:
                  name: {{ template "wopiserver.fullname" . }}-config
              - secret:
                  name: {{ template "wopiserver.fullname" . }}-secrets
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
