apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wopiserver.fullname" . }}
  labels:
    {{- include "wopiserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wopiserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wopiserver.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8880
              protocol: TCP
          volumeMounts:
            - name: {{ include "wopiserver.fullname" . }}-conf
              mountPath: /etc/wopi/wopiserver.conf
              subPath: wopiserver.conf
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
      volumes:
        - name: {{ include "wopiserver.fullname" . }}-conf
          configMap:
            name: {{ include "wopiserver.fullname" . }}-config
            defaultMode: 0744
