apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "revad.fullname" . }}-configmap
  labels:
    {{- include "revad.labels" . | nindent 4 }}
data:
  revad.toml: |
    [shared]
    jwt_secret = "{{ .Values.jwtSecret }}"

{{- if .Values.http }}
    [http]
    address = "0.0.0.0:{{ .Values.http.service.port }}"
{{- end -}}

{{- range $service, $properties := .Values.http.services }}
    [http.services.{{ $service }}]
    {{- range $property, $value := $properties }}
    {{ $property }} = {{ $value | quote }}
    {{- end }}
{{- end }}

{{- if .Values.grpc }}
    [grpc]
    address = "0.0.0.0:{{ .Values.grpc.service.port }}"
{{- end -}}

# {{ .Values.extraRevadConfigs }}
