apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "revad.fullname" . }}
  labels:
    {{- include "revad.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "revad.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "revad.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 20080
              protocol: TCP
            - name: grpc
              containerPort: 20099
              protocol: TCP
          command:
            - /go/bin/revad
          args:
            {{- if .Values.args }}
{{ toYaml .Values.args | indent 14 }}
            {{- else }}
              - "-c"
              - "/etc/revad/revad.toml"
              - "-p"
              - "/var/run/revad.pid"
            {{- end }}
          {{- if .Values.workingDir }}
          workingDir: {{ .Values.workingDir }}
          {{- end }}
          volumeMounts:
            - name: {{ include "revad.fullname" . }}-configfiles
              mountPath: /etc/revad/
        {{- if .Values.gateway }}
        - name: {{ .Chart.Name }}-gateway
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: gateway
              containerPort: 19000
              protocol: TCP
            - name: datagateway
              containerPort: 19001
              protocol: TCP
          command:
            - /go/bin/revad
          args:
              - "-c"
              - "/etc/revad/gateway.toml"
              - "-p"
              - "/var/run/revad.pid"
          volumeMounts:
            - name: {{ include "revad.fullname" . }}-configfiles
              mountPath: /etc/revad/
          {{- end }}
      volumes:
        - name: {{ include "revad.fullname" . }}-configfiles
          configMap:
            name: {{ template "revad.fullname" . }}-config
