apiVersion: v1
kind: Service
metadata:
  name: {{ include "revad.fullname" . }}
  labels:
    {{- include "revad.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- if .Values.service.gateway }}
    - port: {{ .Values.service.gateway.grpc.port }}
      targetPort: gateway
      protocol: TCP
      name: gateway
    - port: {{ .Values.service.gateway.datagateway.port }}
      targetPort: datagateway
      protocol: TCP
      name: datagateway
    {{- end }}
  selector:
    {{- include "revad.selectorLabels" . | nindent 4 }}
