apiVersion: v1
kind: Service
metadata:
  name: {{ include "revad.fullname" . }}
  labels:
    {{- include "revad.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.http.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.grpc.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- if .Values.gateway }}
    - port: {{ .Values.gateway.grpc.service.port }}
      targetPort: gateway
      protocol: TCP
      name: gateway
    - port: {{ .Values.gateway.datagateway.service.port }}
      targetPort: datagateway
      protocol: TCP
      name: datagateway
    {{- end }}
  selector:
    {{- include "revad.selectorLabels" . | nindent 4 }}
